themeVolume: theme # no trailing slash
sidenav: true
enabledPrezs:
  - vocprez
  - spaceprez
vocprezSparqlEndpoint: #{VOCPREZ_SPARQL_ENDPOINT}#
vocprezSparqlUsername: #{VOCPREZ_SPARQL_USERNAME}#
vocprezSparqlPassword: #{VOCPREZ_SPARQL_PASSWORD}#
spaceprezSparqlEndpoint: #{SPACEPREZ_SPARQL_ENDPOINT}#
spaceprezSparqlUsername: #{SPACEPREZ_SPARQL_USERNAME}#
spaceprezSparqlPassword: #{SPACEPREZ_SPARQL_PASSWORD}#
demo: true
debug: true
allowPartialResults: true
searchEndpoints:
  - name: GGIC vocprez
    url: http://ggic.surroundaustralia.com/sparql/
  - name: GSQ vocprez
    url: http://gsq.surroundaustralia.com/sparql/
systemUri: http://ga.surroundaustralia.com
prezTitle: GA prez
prezDesc: prez instance for Geoscience Australia.
vocprezTitle: GA Vocabulary Register
vocprezDesc: Vocabularies managed and published by Geoscience Australia.
vocprezDataUri: http://exampledata.org
spaceprezTitle: GA Spatial Data
spaceprezDesc: Spatial data for Geoscience Australia.
spaceprezDataUri: http://exampledata.org
appName: ga
deploymentMethod: docker # docker, kubernetes or ecs
storageClass: ebs-sc # for kubernetes deployment
version: latest